import type { MovementPattern, OrmLiftKey } from "../types";

export type MuscleGroup =
  | "glutes"
  | "hamstrings"
  | "quads"
  | "calves"
  | "chest"
  | "back"
  | "lats"
  | "traps"
  | "shoulders"
  | "biceps"
  | "triceps"
  | "core"
  | "forearms";

export type Equipment =
  | "barbell"
  | "dumbbell"
  | "kettlebell"
  | "cable"
  | "machine"
  | "band"
  | "bodyweight"
  | "smith"
  | "trap_bar"
  | "other";

export interface ExerciseCatalogEntry {
  id: string;
  canonicalName: string;
  aliases: string[];
  movementPattern: MovementPattern;
  primaryMuscles: MuscleGroup[];
  secondaryMuscles: MuscleGroup[];
  equipment: Equipment;
  anchorLift?: OrmLiftKey;
  modifier?: number;
}

export const EXERCISE_CATALOG_VERSION = 1 as const;

export const exerciseCatalog: ExerciseCatalogEntry[] = [
  {
    id: "barbell_back_squat",
    canonicalName: "Barbell Back Squat",
    aliases: ["Back Squat", "BB Squat", "Barbell Squat"],
    movementPattern: "squat",
    primaryMuscles: ["quads"],
    secondaryMuscles: ["glutes", "core"],
    equipment: "barbell",
    anchorLift: "squat",
    modifier: 1,
  },
  {
    id: "front_squat",
    canonicalName: "Front Squat",
    aliases: ["Barbell Front Squat"],
    movementPattern: "squat",
    primaryMuscles: ["quads"],
    secondaryMuscles: ["glutes", "core"],
    equipment: "barbell",
    anchorLift: "squat",
    modifier: 0.9,
  },
  {
    id: "goblet_squat",
    canonicalName: "Goblet Squat",
    aliases: ["KB Goblet Squat", "Dumbbell Goblet Squat"],
    movementPattern: "squat",
    primaryMuscles: ["quads"],
    secondaryMuscles: ["glutes", "core"],
    equipment: "dumbbell",
    anchorLift: "squat",
    modifier: 0.6,
  },
  {
    id: "hack_squat_machine",
    canonicalName: "Hack Squat (Machine)",
    aliases: ["Hack Squat", "Machine Hack Squat"],
    movementPattern: "squat",
    primaryMuscles: ["quads"],
    secondaryMuscles: ["glutes"],
    equipment: "machine",
    anchorLift: "squat",
    modifier: 0.75,
  },
  {
    id: "leg_press",
    canonicalName: "Leg Press",
    aliases: ["45 Degree Leg Press", "Horizontal Leg Press"],
    movementPattern: "squat",
    primaryMuscles: ["quads"],
    secondaryMuscles: ["glutes"],
    equipment: "machine",
    anchorLift: "squat",
    modifier: 0.85,
  },
  {
    id: "smith_machine_squat",
    canonicalName: "Smith Machine Squat",
    aliases: ["Smith Squat"],
    movementPattern: "squat",
    primaryMuscles: ["quads"],
    secondaryMuscles: ["glutes", "core"],
    equipment: "smith",
    anchorLift: "squat",
    modifier: 0.85,
  },
  {
    id: "trap_bar_deadlift",
    canonicalName: "Trap Bar Deadlift",
    aliases: ["Hex Bar Deadlift"],
    movementPattern: "hinge",
    primaryMuscles: ["glutes", "hamstrings"],
    secondaryMuscles: ["back", "core"],
    equipment: "trap_bar",
    anchorLift: "deadlift",
    modifier: 0.95,
  },
  {
    id: "conventional_deadlift",
    canonicalName: "Conventional Deadlift",
    aliases: ["Deadlift", "Barbell Deadlift"],
    movementPattern: "hinge",
    primaryMuscles: ["glutes", "hamstrings"],
    secondaryMuscles: ["back", "core"],
    equipment: "barbell",
    anchorLift: "deadlift",
    modifier: 1,
  },
  {
    id: "sumo_deadlift",
    canonicalName: "Sumo Deadlift",
    aliases: ["Sumo DL"],
    movementPattern: "hinge",
    primaryMuscles: ["glutes", "hamstrings"],
    secondaryMuscles: ["quads", "back"],
    equipment: "barbell",
    anchorLift: "deadlift",
    modifier: 0.98,
  },
  {
    id: "romanian_deadlift",
    canonicalName: "Romanian Deadlift",
    aliases: ["RDL", "Barbell RDL"],
    movementPattern: "hinge",
    primaryMuscles: ["hamstrings"],
    secondaryMuscles: ["glutes", "back"],
    equipment: "barbell",
    anchorLift: "deadlift",
    modifier: 0.75,
  },
  {
    id: "stiff_leg_deadlift",
    canonicalName: "Stiff-Leg Deadlift",
    aliases: ["Stiff Leg Deadlift", "SLDL"],
    movementPattern: "hinge",
    primaryMuscles: ["hamstrings"],
    secondaryMuscles: ["glutes", "back"],
    equipment: "barbell",
    anchorLift: "deadlift",
    modifier: 0.7,
  },
  {
    id: "good_morning",
    canonicalName: "Good Morning",
    aliases: ["Barbell Good Morning"],
    movementPattern: "hinge",
    primaryMuscles: ["hamstrings"],
    secondaryMuscles: ["glutes", "back"],
    equipment: "barbell",
    anchorLift: "deadlift",
    modifier: 0.6,
  },
  {
    id: "hip_thrust_barbell",
    canonicalName: "Hip Thrust (Barbell)",
    aliases: ["Barbell Hip Thrust", "Hip Thrust"],
    movementPattern: "hinge",
    primaryMuscles: ["glutes"],
    secondaryMuscles: ["hamstrings", "core"],
    equipment: "barbell",
    anchorLift: "deadlift",
    modifier: 0.7,
  },
  {
    id: "glute_bridge_barbell",
    canonicalName: "Glute Bridge (Barbell)",
    aliases: ["Barbell Glute Bridge"],
    movementPattern: "hinge",
    primaryMuscles: ["glutes"],
    secondaryMuscles: ["hamstrings", "core"],
    equipment: "barbell",
    anchorLift: "deadlift",
    modifier: 0.6,
  },
  {
    id: "bench_press",
    canonicalName: "Bench Press",
    aliases: ["Barbell Bench Press", "Flat Bench Press"],
    movementPattern: "horizontal_push",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["triceps", "shoulders"],
    equipment: "barbell",
    anchorLift: "bench",
    modifier: 1,
  },
  {
    id: "incline_bench_press",
    canonicalName: "Incline Bench Press",
    aliases: ["Barbell Incline Bench Press"],
    movementPattern: "horizontal_push",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["triceps", "shoulders"],
    equipment: "barbell",
    anchorLift: "bench",
    modifier: 0.9,
  },
  {
    id: "decline_bench_press",
    canonicalName: "Decline Bench Press",
    aliases: ["Barbell Decline Bench Press"],
    movementPattern: "horizontal_push",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["triceps"],
    equipment: "barbell",
    anchorLift: "bench",
    modifier: 0.9,
  },
  {
    id: "dumbbell_bench_press",
    canonicalName: "Dumbbell Bench Press",
    aliases: ["DB Bench Press", "Flat DB Press"],
    movementPattern: "horizontal_push",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["triceps", "shoulders"],
    equipment: "dumbbell",
    anchorLift: "bench",
    modifier: 0.8,
  },
  {
    id: "incline_dumbbell_press",
    canonicalName: "Incline Dumbbell Press",
    aliases: ["DB Incline Press"],
    movementPattern: "horizontal_push",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["triceps", "shoulders"],
    equipment: "dumbbell",
    anchorLift: "bench",
    modifier: 0.7,
  },
  {
    id: "overhead_press",
    canonicalName: "Overhead Press",
    aliases: ["OHP", "Barbell Overhead Press", "Military Press"],
    movementPattern: "vertical_push",
    primaryMuscles: ["shoulders"],
    secondaryMuscles: ["triceps", "core"],
    equipment: "barbell",
    anchorLift: "ohp",
    modifier: 1,
  },
  {
    id: "seated_dumbbell_shoulder_press",
    canonicalName: "Seated Dumbbell Shoulder Press",
    aliases: ["DB Shoulder Press", "Seated DB Press"],
    movementPattern: "vertical_push",
    primaryMuscles: ["shoulders"],
    secondaryMuscles: ["triceps"],
    equipment: "dumbbell",
    anchorLift: "ohp",
    modifier: 0.75,
  },
  {
    id: "arnold_press",
    canonicalName: "Arnold Press",
    aliases: ["Dumbbell Arnold Press"],
    movementPattern: "vertical_push",
    primaryMuscles: ["shoulders"],
    secondaryMuscles: ["triceps"],
    equipment: "dumbbell",
    anchorLift: "ohp",
    modifier: 0.7,
  },
  {
    id: "push_press",
    canonicalName: "Push Press",
    aliases: ["Barbell Push Press"],
    movementPattern: "vertical_push",
    primaryMuscles: ["shoulders"],
    secondaryMuscles: ["triceps", "core", "quads"],
    equipment: "barbell",
    anchorLift: "ohp",
    modifier: 0.9,
  },
  {
    id: "pull_up",
    canonicalName: "Pull-Up",
    aliases: ["Pull Up", "Strict Pull-Up"],
    movementPattern: "vertical_pull",
    primaryMuscles: ["lats"],
    secondaryMuscles: ["biceps", "back"],
    equipment: "bodyweight",
    anchorLift: undefined,
    modifier: undefined,
  },
  {
    id: "chin_up",
    canonicalName: "Chin-Up",
    aliases: ["Chin Up"],
    movementPattern: "vertical_pull",
    primaryMuscles: ["lats"],
    secondaryMuscles: ["biceps", "back"],
    equipment: "bodyweight",
    anchorLift: undefined,
    modifier: undefined,
  },
  {
    id: "assisted_pull_up",
    canonicalName: "Assisted Pull-Up",
    aliases: ["Machine Assisted Pull-Up"],
    movementPattern: "vertical_pull",
    primaryMuscles: ["lats"],
    secondaryMuscles: ["biceps", "back"],
    equipment: "machine",
    anchorLift: undefined,
    modifier: undefined,
  },
  {
    id: "lat_pulldown",
    canonicalName: "Lat Pulldown",
    aliases: ["Lat Pull-down", "Cable Pulldown"],
    movementPattern: "vertical_pull",
    primaryMuscles: ["lats"],
    secondaryMuscles: ["biceps", "back"],
    equipment: "cable",
    anchorLift: undefined,
    modifier: undefined,
  },
  {
    id: "close_grip_lat_pulldown",
    canonicalName: "Close-Grip Lat Pulldown",
    aliases: ["V-Bar Pulldown"],
    movementPattern: "vertical_pull",
    primaryMuscles: ["lats"],
    secondaryMuscles: ["biceps", "back"],
    equipment: "cable",
    anchorLift: undefined,
    modifier: undefined,
  },
  {
    id: "wide_grip_lat_pulldown",
    canonicalName: "Wide-Grip Lat Pulldown",
    aliases: ["Wide Pulldown"],
    movementPattern: "vertical_pull",
    primaryMuscles: ["lats"],
    secondaryMuscles: ["biceps", "back"],
    equipment: "cable",
    anchorLift: undefined,
    modifier: undefined,
  },
  {
    id: "seated_cable_row",
    canonicalName: "Seated Cable Row",
    aliases: ["Cable Row"],
    movementPattern: "horizontal_pull",
    primaryMuscles: ["back"],
    secondaryMuscles: ["biceps", "lats"],
    equipment: "cable",
    anchorLift: undefined,
    modifier: undefined,
  },
  {
    id: "chest_supported_row_machine",
    canonicalName: "Chest-Supported Row (Machine)",
    aliases: ["Machine Row", "Supported Row"],
    movementPattern: "horizontal_pull",
    primaryMuscles: ["back"],
    secondaryMuscles: ["biceps", "lats"],
    equipment: "machine",
    anchorLift: undefined,
    modifier: undefined,
  },
  {
    id: "dumbbell_row",
    canonicalName: "Dumbbell Row",
    aliases: ["One-Arm DB Row", "Single-Arm DB Row"],
    movementPattern: "horizontal_pull",
    primaryMuscles: ["back"],
    secondaryMuscles: ["biceps", "lats"],
    equipment: "dumbbell",
    anchorLift: undefined,
    modifier: undefined,
  },
  {
    id: "barbell_row",
    canonicalName: "Barbell Row",
    aliases: ["Bent-Over Row", "BB Row"],
    movementPattern: "horizontal_pull",
    primaryMuscles: ["back"],
    secondaryMuscles: ["biceps", "lats"],
    equipment: "barbell",
    anchorLift: undefined,
    modifier: undefined,
  },
  {
    id: "t_bar_row",
    canonicalName: "T-Bar Row",
    aliases: ["T Bar Row"],
    movementPattern: "horizontal_pull",
    primaryMuscles: ["back"],
    secondaryMuscles: ["biceps", "lats"],
    equipment: "machine",
    anchorLift: undefined,
    modifier: undefined,
  },
  {
    id: "inverted_row",
    canonicalName: "Inverted Row",
    aliases: ["Bodyweight Row"],
    movementPattern: "horizontal_pull",
    primaryMuscles: ["back"],
    secondaryMuscles: ["biceps"],
    equipment: "bodyweight",
    anchorLift: undefined,
    modifier: undefined,
  },
  {
    id: "face_pull",
    canonicalName: "Face Pull",
    aliases: ["Cable Face Pull"],
    movementPattern: "isolation_upper",
    primaryMuscles: ["shoulders"],
    secondaryMuscles: ["traps", "back"],
    equipment: "cable",
    anchorLift: "ohp",
    modifier: 0.35,
  },
  {
    id: "rear_delt_fly_dumbbell",
    canonicalName: "Rear Delt Fly (Dumbbell)",
    aliases: ["DB Rear Delt Fly", "Bent-Over Rear Delt Fly"],
    movementPattern: "isolation_upper",
    primaryMuscles: ["shoulders"],
    secondaryMuscles: ["traps"],
    equipment: "dumbbell",
    anchorLift: "ohp",
    modifier: 0.3,
  },
  {
    id: "reverse_pec_deck",
    canonicalName: "Reverse Pec Deck",
    aliases: ["Rear Delt Machine", "Pec Deck Reverse Fly"],
    movementPattern: "isolation_upper",
    primaryMuscles: ["shoulders"],
    secondaryMuscles: ["traps"],
    equipment: "machine",
    anchorLift: "ohp",
    modifier: 0.35,
  },
  {
    id: "shrug_dumbbell",
    canonicalName: "Shrug (Dumbbell)",
    aliases: ["DB Shrug"],
    movementPattern: "isolation_upper",
    primaryMuscles: ["traps"],
    secondaryMuscles: ["forearms"],
    equipment: "dumbbell",
    anchorLift: "deadlift",
    modifier: 0.4,
  },
  {
    id: "shrug_barbell",
    canonicalName: "Shrug (Barbell)",
    aliases: ["BB Shrug", "Barbell Shrug"],
    movementPattern: "isolation_upper",
    primaryMuscles: ["traps"],
    secondaryMuscles: ["forearms"],
    equipment: "barbell",
    anchorLift: "deadlift",
    modifier: 0.45,
  },
  {
    id: "straight_arm_pulldown",
    canonicalName: "Straight-Arm Pulldown",
    aliases: ["Cable Pullover", "Straight Arm Pulldown"],
    movementPattern: "isolation_upper",
    primaryMuscles: ["lats"],
    secondaryMuscles: ["triceps"],
    equipment: "cable",
    anchorLift: "deadlift",
    modifier: 0.35,
  },
  {
    id: "bulgarian_split_squat",
    canonicalName: "Bulgarian Split Squat",
    aliases: ["BSS", "DB Bulgarian Split Squat"],
    movementPattern: "squat",
    primaryMuscles: ["quads"],
    secondaryMuscles: ["glutes", "core"],
    equipment: "dumbbell",
    anchorLift: "squat",
    modifier: 0.6,
  },
  {
    id: "walking_lunge",
    canonicalName: "Walking Lunge",
    aliases: ["DB Walking Lunge", "Lunge Walk"],
    movementPattern: "squat",
    primaryMuscles: ["quads"],
    secondaryMuscles: ["glutes", "core"],
    equipment: "dumbbell",
    anchorLift: "squat",
    modifier: 0.55,
  },
  {
    id: "reverse_lunge",
    canonicalName: "Reverse Lunge",
    aliases: ["DB Reverse Lunge"],
    movementPattern: "squat",
    primaryMuscles: ["quads"],
    secondaryMuscles: ["glutes", "core"],
    equipment: "dumbbell",
    anchorLift: "squat",
    modifier: 0.55,
  },
  {
    id: "step_up",
    canonicalName: "Step-Up",
    aliases: ["DB Step Up"],
    movementPattern: "squat",
    primaryMuscles: ["quads"],
    secondaryMuscles: ["glutes"],
    equipment: "dumbbell",
    anchorLift: "squat",
    modifier: 0.5,
  },
  {
    id: "leg_extension",
    canonicalName: "Leg Extension",
    aliases: ["Machine Leg Extension"],
    movementPattern: "isolation_lower",
    primaryMuscles: ["quads"],
    secondaryMuscles: [],
    equipment: "machine",
    anchorLift: "squat",
    modifier: 0.35,
  },
  {
    id: "seated_leg_curl",
    canonicalName: "Seated Leg Curl",
    aliases: ["Leg Curl (Seated)"],
    movementPattern: "isolation_lower",
    primaryMuscles: ["hamstrings"],
    secondaryMuscles: [],
    equipment: "machine",
    anchorLift: "deadlift",
    modifier: 0.35,
  },
  {
    id: "lying_leg_curl",
    canonicalName: "Lying Leg Curl",
    aliases: ["Leg Curl (Lying)"],
    movementPattern: "isolation_lower",
    primaryMuscles: ["hamstrings"],
    secondaryMuscles: [],
    equipment: "machine",
    anchorLift: "deadlift",
    modifier: 0.35,
  },
  {
    id: "standing_leg_curl",
    canonicalName: "Standing Leg Curl",
    aliases: ["Leg Curl (Standing)"],
    movementPattern: "isolation_lower",
    primaryMuscles: ["hamstrings"],
    secondaryMuscles: [],
    equipment: "machine",
    anchorLift: "deadlift",
    modifier: 0.35,
  },
  {
    id: "calf_raise_standing",
    canonicalName: "Calf Raise (Standing)",
    aliases: ["Standing Calf Raise"],
    movementPattern: "isolation_lower",
    primaryMuscles: ["calves"],
    secondaryMuscles: [],
    equipment: "machine",
    anchorLift: "squat",
    modifier: 0.4,
  },
  {
    id: "calf_raise_seated",
    canonicalName: "Calf Raise (Seated)",
    aliases: ["Seated Calf Raise"],
    movementPattern: "isolation_lower",
    primaryMuscles: ["calves"],
    secondaryMuscles: [],
    equipment: "machine",
    anchorLift: "squat",
    modifier: 0.35,
  },
  {
    id: "hip_abduction_machine",
    canonicalName: "Hip Abduction (Machine)",
    aliases: ["Hip Abductor", "Abductor Machine"],
    movementPattern: "isolation_lower",
    primaryMuscles: ["glutes"],
    secondaryMuscles: [],
    equipment: "machine",
    anchorLift: "deadlift",
    modifier: 0.3,
  },
  {
    id: "hip_adduction_machine",
    canonicalName: "Hip Adduction (Machine)",
    aliases: ["Adductor Machine", "Hip Adductor"],
    movementPattern: "isolation_lower",
    primaryMuscles: ["quads"],
    secondaryMuscles: ["glutes"],
    equipment: "machine",
    anchorLift: "squat",
    modifier: 0.3,
  },
  {
    id: "cable_glute_kickback",
    canonicalName: "Cable Glute Kickback",
    aliases: ["Cable Kickback", "Glute Kickback"],
    movementPattern: "isolation_lower",
    primaryMuscles: ["glutes"],
    secondaryMuscles: [],
    equipment: "cable",
    anchorLift: "deadlift",
    modifier: 0.3,
  },
  {
    id: "cable_standing_hip_abduction",
    canonicalName: "Cable Standing Hip Abduction",
    aliases: ["Standing Hip Abduction"],
    movementPattern: "isolation_lower",
    primaryMuscles: ["glutes"],
    secondaryMuscles: [],
    equipment: "cable",
    anchorLift: "deadlift",
    modifier: 0.25,
  },
  {
    id: "back_extension",
    canonicalName: "Back Extension",
    aliases: ["Hyperextension", "Roman Chair Back Extension"],
    movementPattern: "hinge",
    primaryMuscles: ["glutes", "hamstrings"],
    secondaryMuscles: ["back"],
    equipment: "bodyweight",
    anchorLift: "deadlift",
    modifier: 0.5,
  },
  {
    id: "single_leg_rdl_dumbbell",
    canonicalName: "Single-Leg RDL (Dumbbell)",
    aliases: ["Single Leg RDL", "DB Single-Leg RDL"],
    movementPattern: "hinge",
    primaryMuscles: ["hamstrings"],
    secondaryMuscles: ["glutes", "core"],
    equipment: "dumbbell",
    anchorLift: "deadlift",
    modifier: 0.55,
  },
  {
    id: "kettlebell_swing",
    canonicalName: "Kettlebell Swing",
    aliases: ["KB Swing"],
    movementPattern: "hinge",
    primaryMuscles: ["glutes", "hamstrings"],
    secondaryMuscles: ["core"],
    equipment: "kettlebell",
    anchorLift: "deadlift",
    modifier: 0.5,
  },
  {
    id: "push_up",
    canonicalName: "Push-Up",
    aliases: ["Push Up"],
    movementPattern: "horizontal_push",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["triceps", "shoulders"],
    equipment: "bodyweight",
    anchorLift: "bench",
    modifier: 0.5,
  },
  {
    id: "dumbbell_fly",
    canonicalName: "Dumbbell Fly",
    aliases: ["DB Fly", "Flat Dumbbell Fly"],
    movementPattern: "isolation_upper",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["shoulders"],
    equipment: "dumbbell",
    anchorLift: "bench",
    modifier: 0.3,
  },
  {
    id: "cable_fly",
    canonicalName: "Cable Fly",
    aliases: ["Cable Crossover", "Cable Chest Fly"],
    movementPattern: "isolation_upper",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["shoulders"],
    equipment: "cable",
    anchorLift: "bench",
    modifier: 0.3,
  },
  {
    id: "tricep_pushdown",
    canonicalName: "Tricep Pushdown",
    aliases: ["Cable Tricep Pushdown"],
    movementPattern: "isolation_upper",
    primaryMuscles: ["triceps"],
    secondaryMuscles: [],
    equipment: "cable",
    anchorLift: "bench",
    modifier: 0.3,
  },
  {
    id: "overhead_tricep_extension_cable",
    canonicalName: "Overhead Tricep Extension (Cable)",
    aliases: ["Cable Overhead Tricep Extension"],
    movementPattern: "isolation_upper",
    primaryMuscles: ["triceps"],
    secondaryMuscles: [],
    equipment: "cable",
    anchorLift: "ohp",
    modifier: 0.28,
  },
  {
    id: "skullcrusher",
    canonicalName: "Skullcrusher",
    aliases: ["Lying Tricep Extension", "EZ-Bar Skullcrusher"],
    movementPattern: "isolation_upper",
    primaryMuscles: ["triceps"],
    secondaryMuscles: [],
    equipment: "barbell",
    anchorLift: "bench",
    modifier: 0.3,
  },
  {
    id: "dumbbell_bicep_curl",
    canonicalName: "Dumbbell Bicep Curl",
    aliases: ["DB Curl", "Biceps Curl"],
    movementPattern: "isolation_upper",
    primaryMuscles: ["biceps"],
    secondaryMuscles: [],
    equipment: "dumbbell",
    anchorLift: "bench",
    modifier: 0.25,
  },
  {
    id: "hammer_curl",
    canonicalName: "Hammer Curl",
    aliases: ["DB Hammer Curl"],
    movementPattern: "isolation_upper",
    primaryMuscles: ["biceps"],
    secondaryMuscles: ["forearms"],
    equipment: "dumbbell",
    anchorLift: "bench",
    modifier: 0.25,
  },
  {
    id: "cable_bicep_curl",
    canonicalName: "Cable Bicep Curl",
    aliases: ["Cable Curl"],
    movementPattern: "isolation_upper",
    primaryMuscles: ["biceps"],
    secondaryMuscles: [],
    equipment: "cable",
    anchorLift: "bench",
    modifier: 0.25,
  },
  {
    id: "preacher_curl_machine",
    canonicalName: "Preacher Curl (Machine)",
    aliases: ["Machine Preacher Curl"],
    movementPattern: "isolation_upper",
    primaryMuscles: ["biceps"],
    secondaryMuscles: [],
    equipment: "machine",
    anchorLift: "bench",
    modifier: 0.25,
  },
  {
    id: "lateral_raise",
    canonicalName: "Lateral Raise",
    aliases: ["DB Lateral Raise", "Side Lateral Raise"],
    movementPattern: "isolation_upper",
    primaryMuscles: ["shoulders"],
    secondaryMuscles: [],
    equipment: "dumbbell",
    anchorLift: "ohp",
    modifier: 0.25,
  },
  {
    id: "cable_lateral_raise",
    canonicalName: "Cable Lateral Raise",
    aliases: ["Single-Arm Cable Lateral Raise"],
    movementPattern: "isolation_upper",
    primaryMuscles: ["shoulders"],
    secondaryMuscles: [],
    equipment: "cable",
    anchorLift: "ohp",
    modifier: 0.25,
  },
  {
    id: "front_raise",
    canonicalName: "Front Raise",
    aliases: ["DB Front Raise"],
    movementPattern: "isolation_upper",
    primaryMuscles: ["shoulders"],
    secondaryMuscles: [],
    equipment: "dumbbell",
    anchorLift: "ohp",
    modifier: 0.22,
  },
  {
    id: "tricep_dip_bench",
    canonicalName: "Tricep Dip (Bench)",
    aliases: ["Bench Dip"],
    movementPattern: "isolation_upper",
    primaryMuscles: ["triceps"],
    secondaryMuscles: ["shoulders"],
    equipment: "bodyweight",
    anchorLift: "bench",
    modifier: 0.35,
  },
  {
    id: "chest_press_machine",
    canonicalName: "Chest Press (Machine)",
    aliases: ["Machine Chest Press"],
    movementPattern: "horizontal_push",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["triceps", "shoulders"],
    equipment: "machine",
    anchorLift: "bench",
    modifier: 0.75,
  },
  {
    id: "shoulder_press_machine",
    canonicalName: "Shoulder Press (Machine)",
    aliases: ["Machine Shoulder Press"],
    movementPattern: "vertical_push",
    primaryMuscles: ["shoulders"],
    secondaryMuscles: ["triceps"],
    equipment: "machine",
    anchorLift: "ohp",
    modifier: 0.8,
  },
  {
    id: "incline_chest_press_machine",
    canonicalName: "Incline Chest Press (Machine)",
    aliases: ["Incline Machine Press"],
    movementPattern: "horizontal_push",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["triceps", "shoulders"],
    equipment: "machine",
    anchorLift: "bench",
    modifier: 0.7,
  },
  {
    id: "plank",
    canonicalName: "Plank",
    aliases: ["Front Plank"],
    movementPattern: "core",
    primaryMuscles: ["core"],
    secondaryMuscles: [],
    equipment: "bodyweight",
    anchorLift: undefined,
    modifier: undefined,
  },
  {
    id: "side_plank",
    canonicalName: "Side Plank",
    aliases: ["Plank (Side)"],
    movementPattern: "core",
    primaryMuscles: ["core"],
    secondaryMuscles: [],
    equipment: "bodyweight",
    anchorLift: undefined,
    modifier: undefined,
  },
  {
    id: "hanging_leg_raise",
    canonicalName: "Hanging Leg Raise",
    aliases: ["Hanging Knee Raise"],
    movementPattern: "core",
    primaryMuscles: ["core"],
    secondaryMuscles: [],
    equipment: "bodyweight",
    anchorLift: undefined,
    modifier: undefined,
  },
  {
    id: "cable_crunch",
    canonicalName: "Cable Crunch",
    aliases: ["Rope Cable Crunch"],
    movementPattern: "core",
    primaryMuscles: ["core"],
    secondaryMuscles: [],
    equipment: "cable",
    anchorLift: undefined,
    modifier: undefined,
  },
  {
    id: "ab_wheel_rollout",
    canonicalName: "Ab Wheel Rollout",
    aliases: ["Ab Wheel"],
    movementPattern: "core",
    primaryMuscles: ["core"],
    secondaryMuscles: [],
    equipment: "other",
    anchorLift: undefined,
    modifier: undefined,
  },
  {
    id: "russian_twist",
    canonicalName: "Russian Twist",
    aliases: ["Weighted Russian Twist"],
    movementPattern: "core",
    primaryMuscles: ["core"],
    secondaryMuscles: [],
    equipment: "other",
    anchorLift: undefined,
    modifier: undefined,
  },
  {
    id: "pallof_press",
    canonicalName: "Pallof Press",
    aliases: ["Cable Pallof Press"],
    movementPattern: "core",
    primaryMuscles: ["core"],
    secondaryMuscles: [],
    equipment: "cable",
    anchorLift: undefined,
    modifier: undefined,
  },
  {
    id: "dead_bug",
    canonicalName: "Dead Bug",
    aliases: ["Deadbug"],
    movementPattern: "core",
    primaryMuscles: ["core"],
    secondaryMuscles: [],
    equipment: "bodyweight",
    anchorLift: undefined,
    modifier: undefined,
  },
  {
    id: "bird_dog",
    canonicalName: "Bird Dog",
    aliases: ["Bird-dog"],
    movementPattern: "core",
    primaryMuscles: ["core"],
    secondaryMuscles: [],
    equipment: "bodyweight",
    anchorLift: undefined,
    modifier: undefined,
  },
  {
    id: "treadmill_run",
    canonicalName: "Treadmill Run",
    aliases: ["Run"],
    movementPattern: "conditioning",
    primaryMuscles: ["core"],
    secondaryMuscles: [],
    equipment: "machine",
    anchorLift: undefined,
    modifier: undefined,
  },
  {
    id: "stationary_bike",
    canonicalName: "Stationary Bike",
    aliases: ["Bike", "Cycling"],
    movementPattern: "conditioning",
    primaryMuscles: ["core"],
    secondaryMuscles: [],
    equipment: "machine",
    anchorLift: undefined,
    modifier: undefined,
  },
  {
    id: "rowing_machine",
    canonicalName: "Rowing Machine",
    aliases: ["Rower"],
    movementPattern: "conditioning",
    primaryMuscles: ["back"],
    secondaryMuscles: ["core"],
    equipment: "machine",
    anchorLift: undefined,
    modifier: undefined,
  },
  {
    id: "jump_rope",
    canonicalName: "Jump Rope",
    aliases: ["Skipping Rope"],
    movementPattern: "conditioning",
    primaryMuscles: ["calves"],
    secondaryMuscles: ["core"],
    equipment: "other",
    anchorLift: undefined,
    modifier: undefined,
  },
  {
    id: "sprints",
    canonicalName: "Sprints",
    aliases: ["Sprint"],
    movementPattern: "conditioning",
    primaryMuscles: ["quads"],
    secondaryMuscles: ["hamstrings", "glutes"],
    equipment: "other",
    anchorLift: undefined,
    modifier: undefined,
  },
  {
    id: "farmer_s_carry",
    canonicalName: "Farmer's Carry",
    aliases: ["Farmers Walk"],
    movementPattern: "carry",
    primaryMuscles: ["forearms"],
    secondaryMuscles: ["core", "traps"],
    equipment: "dumbbell",
    anchorLift: "deadlift",
    modifier: 0.25,
  },
  {
    id: "suitcase_carry",
    canonicalName: "Suitcase Carry",
    aliases: ["Single-Arm Carry"],
    movementPattern: "carry",
    primaryMuscles: ["forearms"],
    secondaryMuscles: ["core"],
    equipment: "dumbbell",
    anchorLift: "deadlift",
    modifier: 0.22,
  },
  {
    id: "overhead_carry",
    canonicalName: "Overhead Carry",
    aliases: ["DB Overhead Carry"],
    movementPattern: "carry",
    primaryMuscles: ["shoulders"],
    secondaryMuscles: ["core"],
    equipment: "dumbbell",
    anchorLift: "ohp",
    modifier: 0.22,
  },
  {
    id: "box_squat",
    canonicalName: "Box Squat",
    aliases: ["BB Box Squat"],
    movementPattern: "squat",
    primaryMuscles: ["quads"],
    secondaryMuscles: ["glutes", "core"],
    equipment: "barbell",
    anchorLift: "squat",
    modifier: 0.9,
  },
  {
    id: "paused_squat",
    canonicalName: "Paused Squat",
    aliases: ["Pause Squat"],
    movementPattern: "squat",
    primaryMuscles: ["quads"],
    secondaryMuscles: ["glutes", "core"],
    equipment: "barbell",
    anchorLift: "squat",
    modifier: 0.85,
  },
  {
    id: "tempo_squat",
    canonicalName: "Tempo Squat",
    aliases: ["Slow Squat", "3-0-3 Squat"],
    movementPattern: "squat",
    primaryMuscles: ["quads"],
    secondaryMuscles: ["glutes", "core"],
    equipment: "barbell",
    anchorLift: "squat",
    modifier: 0.8,
  },
  {
    id: "smith_machine_split_squat",
    canonicalName: "Smith Machine Split Squat",
    aliases: ["Smith Split Squat"],
    movementPattern: "squat",
    primaryMuscles: ["quads"],
    secondaryMuscles: ["glutes"],
    equipment: "smith",
    anchorLift: "squat",
    modifier: 0.6,
  },
  {
    id: "hack_squat_smith",
    canonicalName: "Hack Squat (Smith)",
    aliases: ["Smith Hack Squat"],
    movementPattern: "squat",
    primaryMuscles: ["quads"],
    secondaryMuscles: ["glutes"],
    equipment: "smith",
    anchorLift: "squat",
    modifier: 0.75,
  },
  {
    id: "sissy_squat",
    canonicalName: "Sissy Squat",
    aliases: ["Sissy Squats"],
    movementPattern: "squat",
    primaryMuscles: ["quads"],
    secondaryMuscles: ["core"],
    equipment: "bodyweight",
    anchorLift: "squat",
    modifier: 0.35,
  },
  {
    id: "belt_squat",
    canonicalName: "Belt Squat",
    aliases: ["Belt Squat Machine"],
    movementPattern: "squat",
    primaryMuscles: ["quads"],
    secondaryMuscles: ["glutes"],
    equipment: "machine",
    anchorLift: "squat",
    modifier: 0.85,
  },
  {
    id: "safety_bar_squat",
    canonicalName: "Safety Bar Squat",
    aliases: ["SSB Squat"],
    movementPattern: "squat",
    primaryMuscles: ["quads"],
    secondaryMuscles: ["glutes", "core"],
    equipment: "barbell",
    anchorLift: "squat",
    modifier: 0.95,
  },
  {
    id: "zercher_squat",
    canonicalName: "Zercher Squat",
    aliases: ["Zercher"],
    movementPattern: "squat",
    primaryMuscles: ["quads"],
    secondaryMuscles: ["core", "glutes"],
    equipment: "barbell",
    anchorLift: "squat",
    modifier: 0.8,
  },
  {
    id: "walking_lunge_barbell",
    canonicalName: "Walking Lunge (Barbell)",
    aliases: ["BB Walking Lunge"],
    movementPattern: "squat",
    primaryMuscles: ["quads"],
    secondaryMuscles: ["glutes", "core"],
    equipment: "barbell",
    anchorLift: "squat",
    modifier: 0.6,
  },
  {
    id: "lateral_lunge",
    canonicalName: "Lateral Lunge",
    aliases: ["Side Lunge"],
    movementPattern: "squat",
    primaryMuscles: ["quads"],
    secondaryMuscles: ["glutes"],
    equipment: "dumbbell",
    anchorLift: "squat",
    modifier: 0.5,
  },
  {
    id: "curtsy_lunge",
    canonicalName: "Curtsy Lunge",
    aliases: ["Curtsy Lunges"],
    movementPattern: "squat",
    primaryMuscles: ["glutes"],
    secondaryMuscles: ["quads"],
    equipment: "dumbbell",
    anchorLift: "squat",
    modifier: 0.45,
  },
  {
    id: "hack_squat_plate_loaded",
    canonicalName: "Hack Squat (Plate Loaded)",
    aliases: ["Plate Loaded Hack Squat"],
    movementPattern: "squat",
    primaryMuscles: ["quads"],
    secondaryMuscles: ["glutes"],
    equipment: "machine",
    anchorLift: "squat",
    modifier: 0.75,
  },
  {
    id: "deadlift_deficit",
    canonicalName: "Deadlift (Deficit)",
    aliases: ["Deficit Deadlift"],
    movementPattern: "hinge",
    primaryMuscles: ["glutes", "hamstrings"],
    secondaryMuscles: ["back", "core"],
    equipment: "barbell",
    anchorLift: "deadlift",
    modifier: 0.9,
  },
  {
    id: "deadlift_rack_pull",
    canonicalName: "Deadlift (Rack Pull)",
    aliases: ["Rack Pull"],
    movementPattern: "hinge",
    primaryMuscles: ["glutes", "hamstrings"],
    secondaryMuscles: ["back"],
    equipment: "barbell",
    anchorLift: "deadlift",
    modifier: 0.9,
  },
  {
    id: "snatch_grip_deadlift",
    canonicalName: "Snatch-Grip Deadlift",
    aliases: ["Snatch Grip DL"],
    movementPattern: "hinge",
    primaryMuscles: ["glutes", "hamstrings"],
    secondaryMuscles: ["back"],
    equipment: "barbell",
    anchorLift: "deadlift",
    modifier: 0.9,
  },
  {
    id: "dumbbell_romanian_deadlift",
    canonicalName: "Dumbbell Romanian Deadlift",
    aliases: ["DB RDL"],
    movementPattern: "hinge",
    primaryMuscles: ["hamstrings"],
    secondaryMuscles: ["glutes", "back"],
    equipment: "dumbbell",
    anchorLift: "deadlift",
    modifier: 0.6,
  },
  {
    id: "cable_pull_through",
    canonicalName: "Cable Pull Through",
    aliases: ["Cable Pull-Through"],
    movementPattern: "hinge",
    primaryMuscles: ["glutes"],
    secondaryMuscles: ["hamstrings"],
    equipment: "cable",
    anchorLift: "deadlift",
    modifier: 0.45,
  },
  {
    id: "hip_thrust_machine",
    canonicalName: "Hip Thrust (Machine)",
    aliases: ["Machine Hip Thrust"],
    movementPattern: "hinge",
    primaryMuscles: ["glutes"],
    secondaryMuscles: ["hamstrings"],
    equipment: "machine",
    anchorLift: "deadlift",
    modifier: 0.75,
  },
  {
    id: "glute_bridge_banded",
    canonicalName: "Glute Bridge (Banded)",
    aliases: ["Banded Glute Bridge"],
    movementPattern: "isolation_lower",
    primaryMuscles: ["glutes"],
    secondaryMuscles: [],
    equipment: "band",
    anchorLift: "deadlift",
    modifier: 0.25,
  },
  {
    id: "nordic_hamstring_curl",
    canonicalName: "Nordic Hamstring Curl",
    aliases: ["Nordic Curl"],
    movementPattern: "isolation_lower",
    primaryMuscles: ["hamstrings"],
    secondaryMuscles: [],
    equipment: "bodyweight",
    anchorLift: "deadlift",
    modifier: 0.25,
  },
  {
    id: "kettlebell_deadlift",
    canonicalName: "Kettlebell Deadlift",
    aliases: ["KB Deadlift"],
    movementPattern: "hinge",
    primaryMuscles: ["glutes", "hamstrings"],
    secondaryMuscles: ["back"],
    equipment: "kettlebell",
    anchorLift: "deadlift",
    modifier: 0.6,
  },
  {
    id: "cable_good_morning",
    canonicalName: "Cable Good Morning",
    aliases: ["Good Morning (Cable)"],
    movementPattern: "hinge",
    primaryMuscles: ["hamstrings"],
    secondaryMuscles: ["glutes", "back"],
    equipment: "cable",
    anchorLift: "deadlift",
    modifier: 0.4,
  },
  {
    id: "dumbbell_shoulder_press_standing",
    canonicalName: "Dumbbell Shoulder Press (Standing)",
    aliases: ["Standing DB Press"],
    movementPattern: "vertical_push",
    primaryMuscles: ["shoulders"],
    secondaryMuscles: ["triceps", "core"],
    equipment: "dumbbell",
    anchorLift: "ohp",
    modifier: 0.7,
  },
  {
    id: "landmine_press",
    canonicalName: "Landmine Press",
    aliases: ["Landmine Shoulder Press"],
    movementPattern: "vertical_push",
    primaryMuscles: ["shoulders"],
    secondaryMuscles: ["triceps", "core"],
    equipment: "barbell",
    anchorLift: "ohp",
    modifier: 0.65,
  },
  {
    id: "push_up_incline",
    canonicalName: "Push-Up (Incline)",
    aliases: ["Incline Pushup"],
    movementPattern: "horizontal_push",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["triceps", "shoulders"],
    equipment: "bodyweight",
    anchorLift: "bench",
    modifier: 0.45,
  },
  {
    id: "push_up_decline",
    canonicalName: "Push-Up (Decline)",
    aliases: ["Decline Pushup"],
    movementPattern: "horizontal_push",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["triceps", "shoulders"],
    equipment: "bodyweight",
    anchorLift: "bench",
    modifier: 0.55,
  },
  {
    id: "dips_parallel_bars",
    canonicalName: "Dips (Parallel Bars)",
    aliases: ["Dips", "Chest Dip"],
    movementPattern: "horizontal_push",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["triceps", "shoulders"],
    equipment: "bodyweight",
    anchorLift: "bench",
    modifier: 0.6,
  },
  {
    id: "cable_chest_press",
    canonicalName: "Cable Chest Press",
    aliases: ["Standing Cable Press"],
    movementPattern: "horizontal_push",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["triceps", "shoulders"],
    equipment: "cable",
    anchorLift: "bench",
    modifier: 0.55,
  },
  {
    id: "pec_deck",
    canonicalName: "Pec Deck",
    aliases: ["Machine Fly", "Pec Deck Fly"],
    movementPattern: "isolation_upper",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["shoulders"],
    equipment: "machine",
    anchorLift: "bench",
    modifier: 0.35,
  },
  {
    id: "incline_dumbbell_fly",
    canonicalName: "Incline Dumbbell Fly",
    aliases: ["Incline DB Fly"],
    movementPattern: "isolation_upper",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["shoulders"],
    equipment: "dumbbell",
    anchorLift: "bench",
    modifier: 0.3,
  },
  {
    id: "seated_machine_dip",
    canonicalName: "Seated Machine Dip",
    aliases: ["Dip Machine"],
    movementPattern: "horizontal_push",
    primaryMuscles: ["triceps"],
    secondaryMuscles: ["chest", "shoulders"],
    equipment: "machine",
    anchorLift: "bench",
    modifier: 0.6,
  },
  {
    id: "cable_tricep_kickback",
    canonicalName: "Cable Tricep Kickback",
    aliases: ["Tricep Kickback (Cable)"],
    movementPattern: "isolation_upper",
    primaryMuscles: ["triceps"],
    secondaryMuscles: [],
    equipment: "cable",
    anchorLift: "bench",
    modifier: 0.25,
  },
  {
    id: "tricep_extension_dumbbell_overhead",
    canonicalName: "Tricep Extension (Dumbbell Overhead)",
    aliases: ["DB Overhead Tricep Extension"],
    movementPattern: "isolation_upper",
    primaryMuscles: ["triceps"],
    secondaryMuscles: [],
    equipment: "dumbbell",
    anchorLift: "ohp",
    modifier: 0.22,
  },
  {
    id: "close_grip_bench_press",
    canonicalName: "Close-Grip Bench Press",
    aliases: ["CGBP", "Close Grip Bench"],
    movementPattern: "horizontal_push",
    primaryMuscles: ["triceps"],
    secondaryMuscles: ["chest", "shoulders"],
    equipment: "barbell",
    anchorLift: "bench",
    modifier: 0.95,
  },
  {
    id: "incline_push_press",
    canonicalName: "Incline Push Press",
    aliases: ["Push Press (Incline?)"],
    movementPattern: "vertical_push",
    primaryMuscles: ["shoulders"],
    secondaryMuscles: ["triceps", "core"],
    equipment: "barbell",
    anchorLift: "ohp",
    modifier: 0.9,
  },
  {
    id: "single_arm_cable_row",
    canonicalName: "Single-Arm Cable Row",
    aliases: ["One-Arm Cable Row"],
    movementPattern: "horizontal_pull",
    primaryMuscles: ["back"],
    secondaryMuscles: ["biceps", "lats"],
    equipment: "cable",
    anchorLift: undefined,
    modifier: undefined,
  },
  {
    id: "meadows_row",
    canonicalName: "Meadows Row",
    aliases: ["Landmine Row (Meadows)"],
    movementPattern: "horizontal_pull",
    primaryMuscles: ["back"],
    secondaryMuscles: ["biceps", "lats"],
    equipment: "barbell",
    anchorLift: undefined,
    modifier: undefined,
  },
  {
    id: "landmine_row",
    canonicalName: "Landmine Row",
    aliases: ["T-Bar Row (Landmine)"],
    movementPattern: "horizontal_pull",
    primaryMuscles: ["back"],
    secondaryMuscles: ["biceps", "lats"],
    equipment: "barbell",
    anchorLift: undefined,
    modifier: undefined,
  },
  {
    id: "pendlay_row",
    canonicalName: "Pendlay Row",
    aliases: ["Pendlay"],
    movementPattern: "horizontal_pull",
    primaryMuscles: ["back"],
    secondaryMuscles: ["biceps", "lats"],
    equipment: "barbell",
    anchorLift: undefined,
    modifier: undefined,
  },
  {
    id: "cable_pullover",
    canonicalName: "Cable Pullover",
    aliases: ["Straight-Arm Pullover"],
    movementPattern: "isolation_upper",
    primaryMuscles: ["lats"],
    secondaryMuscles: ["triceps"],
    equipment: "cable",
    anchorLift: "deadlift",
    modifier: 0.3,
  },
  {
    id: "dumbbell_pullover",
    canonicalName: "Dumbbell Pullover",
    aliases: ["DB Pullover"],
    movementPattern: "isolation_upper",
    primaryMuscles: ["lats"],
    secondaryMuscles: ["chest"],
    equipment: "dumbbell",
    anchorLift: "deadlift",
    modifier: 0.25,
  },
  {
    id: "ez_bar_curl",
    canonicalName: "EZ-Bar Curl",
    aliases: ["EZ Curl", "EZ Bar Bicep Curl"],
    movementPattern: "isolation_upper",
    primaryMuscles: ["biceps"],
    secondaryMuscles: [],
    equipment: "barbell",
    anchorLift: "bench",
    modifier: 0.28,
  },
  {
    id: "concentration_curl",
    canonicalName: "Concentration Curl",
    aliases: ["DB Concentration Curl"],
    movementPattern: "isolation_upper",
    primaryMuscles: ["biceps"],
    secondaryMuscles: [],
    equipment: "dumbbell",
    anchorLift: "bench",
    modifier: 0.22,
  },
  {
    id: "incline_dumbbell_curl",
    canonicalName: "Incline Dumbbell Curl",
    aliases: ["Incline DB Curl"],
    movementPattern: "isolation_upper",
    primaryMuscles: ["biceps"],
    secondaryMuscles: [],
    equipment: "dumbbell",
    anchorLift: "bench",
    modifier: 0.22,
  },
  {
    id: "spider_curl",
    canonicalName: "Spider Curl",
    aliases: ["Spider Curls"],
    movementPattern: "isolation_upper",
    primaryMuscles: ["biceps"],
    secondaryMuscles: [],
    equipment: "dumbbell",
    anchorLift: "bench",
    modifier: 0.22,
  },
  {
    id: "cable_rope_hammer_curl",
    canonicalName: "Cable Rope Hammer Curl",
    aliases: ["Rope Hammer Curl"],
    movementPattern: "isolation_upper",
    primaryMuscles: ["biceps"],
    secondaryMuscles: ["forearms"],
    equipment: "cable",
    anchorLift: "bench",
    modifier: 0.22,
  },
  {
    id: "reverse_curl",
    canonicalName: "Reverse Curl",
    aliases: ["EZ Reverse Curl"],
    movementPattern: "isolation_upper",
    primaryMuscles: ["forearms"],
    secondaryMuscles: ["biceps"],
    equipment: "barbell",
    anchorLift: "bench",
    modifier: 0.22,
  },
  {
    id: "wrist_curl",
    canonicalName: "Wrist Curl",
    aliases: ["DB Wrist Curl"],
    movementPattern: "isolation_upper",
    primaryMuscles: ["forearms"],
    secondaryMuscles: [],
    equipment: "dumbbell",
    anchorLift: "bench",
    modifier: 0.18,
  },
  {
    id: "tricep_rope_pushdown",
    canonicalName: "Tricep Rope Pushdown",
    aliases: ["Rope Pushdown"],
    movementPattern: "isolation_upper",
    primaryMuscles: ["triceps"],
    secondaryMuscles: [],
    equipment: "cable",
    anchorLift: "bench",
    modifier: 0.28,
  },
  {
    id: "single_arm_tricep_pushdown",
    canonicalName: "Single-Arm Tricep Pushdown",
    aliases: ["One-Arm Pushdown"],
    movementPattern: "isolation_upper",
    primaryMuscles: ["triceps"],
    secondaryMuscles: [],
    equipment: "cable",
    anchorLift: "bench",
    modifier: 0.25,
  },
  {
    id: "tricep_pressdown_v_bar",
    canonicalName: "Tricep Pressdown (V-Bar)",
    aliases: ["V-Bar Pushdown"],
    movementPattern: "isolation_upper",
    primaryMuscles: ["triceps"],
    secondaryMuscles: [],
    equipment: "cable",
    anchorLift: "bench",
    modifier: 0.28,
  },
  {
    id: "face_pull_rope",
    canonicalName: "Face Pull (Rope)",
    aliases: ["Rope Face Pull"],
    movementPattern: "isolation_upper",
    primaryMuscles: ["shoulders"],
    secondaryMuscles: ["traps", "back"],
    equipment: "cable",
    anchorLift: "ohp",
    modifier: 0.35,
  },
  {
    id: "band_pull_apart",
    canonicalName: "Band Pull-Apart",
    aliases: ["Pull Apart"],
    movementPattern: "isolation_upper",
    primaryMuscles: ["shoulders"],
    secondaryMuscles: ["back"],
    equipment: "band",
    anchorLift: "ohp",
    modifier: 0.18,
  },
  {
    id: "glute_ham_raise",
    canonicalName: "Glute-Ham Raise",
    aliases: ["GHR"],
    movementPattern: "isolation_lower",
    primaryMuscles: ["hamstrings"],
    secondaryMuscles: ["glutes"],
    equipment: "machine",
    anchorLift: "deadlift",
    modifier: 0.3,
  },
  {
    id: "seated_calf_raise_dumbbell",
    canonicalName: "Seated Calf Raise (Dumbbell)",
    aliases: ["DB Seated Calf Raise"],
    movementPattern: "isolation_lower",
    primaryMuscles: ["calves"],
    secondaryMuscles: [],
    equipment: "dumbbell",
    anchorLift: "squat",
    modifier: 0.25,
  },
  {
    id: "single_leg_calf_raise",
    canonicalName: "Single-Leg Calf Raise",
    aliases: ["Single Leg Calf Raise"],
    movementPattern: "isolation_lower",
    primaryMuscles: ["calves"],
    secondaryMuscles: [],
    equipment: "bodyweight",
    anchorLift: "squat",
    modifier: 0.25,
  },
  {
    id: "donkey_calf_raise",
    canonicalName: "Donkey Calf Raise",
    aliases: ["Donkey Raises"],
    movementPattern: "isolation_lower",
    primaryMuscles: ["calves"],
    secondaryMuscles: [],
    equipment: "machine",
    anchorLift: "squat",
    modifier: 0.3,
  },
  {
    id: "glute_medius_abduction_band",
    canonicalName: "Glute Medius Abduction (Band)",
    aliases: ["Band Abduction"],
    movementPattern: "isolation_lower",
    primaryMuscles: ["glutes"],
    secondaryMuscles: [],
    equipment: "band",
    anchorLift: "deadlift",
    modifier: 0.18,
  },
  {
    id: "cable_hip_adduction",
    canonicalName: "Cable Hip Adduction",
    aliases: ["Standing Hip Adduction"],
    movementPattern: "isolation_lower",
    primaryMuscles: ["quads"],
    secondaryMuscles: ["glutes"],
    equipment: "cable",
    anchorLift: "squat",
    modifier: 0.2,
  },
  {
    id: "cable_hip_flexion",
    canonicalName: "Cable Hip Flexion",
    aliases: ["Standing Hip Flexion"],
    movementPattern: "isolation_lower",
    primaryMuscles: ["quads"],
    secondaryMuscles: [],
    equipment: "cable",
    anchorLift: "squat",
    modifier: 0.2,
  },
  {
    id: "stepmill",
    canonicalName: "Stepmill",
    aliases: ["Stairmaster"],
    movementPattern: "conditioning",
    primaryMuscles: ["glutes"],
    secondaryMuscles: ["quads", "calves"],
    equipment: "machine",
    anchorLift: undefined,
    modifier: undefined,
  },
  {
    id: "sled_push",
    canonicalName: "Sled Push",
    aliases: ["Prowler Push"],
    movementPattern: "conditioning",
    primaryMuscles: ["quads"],
    secondaryMuscles: ["glutes", "core"],
    equipment: "other",
    anchorLift: undefined,
    modifier: undefined,
  },
  {
    id: "sled_pull",
    canonicalName: "Sled Pull",
    aliases: ["Sled Drag"],
    movementPattern: "conditioning",
    primaryMuscles: ["hamstrings"],
    secondaryMuscles: ["glutes", "core"],
    equipment: "other",
    anchorLift: undefined,
    modifier: undefined,
  },
  {
    id: "leg_press_single_leg",
    canonicalName: "Leg Press (Single-Leg)",
    aliases: ["Single Leg Press"],
    movementPattern: "squat",
    primaryMuscles: ["quads"],
    secondaryMuscles: ["glutes"],
    equipment: "machine",
    anchorLift: "squat",
    modifier: 0.65,
  },
  {
    id: "hip_thrust_smith_machine",
    canonicalName: "Hip Thrust (Smith Machine)",
    aliases: ["Smith Hip Thrust"],
    movementPattern: "hinge",
    primaryMuscles: ["glutes"],
    secondaryMuscles: ["hamstrings"],
    equipment: "smith",
    anchorLift: "deadlift",
    modifier: 0.7,
  },
  {
    id: "mountain_climber",
    canonicalName: "Mountain Climber",
    aliases: ["Mountain Climbers"],
    movementPattern: "conditioning",
    primaryMuscles: ["core"],
    secondaryMuscles: ["shoulders"],
    equipment: "bodyweight",
    anchorLift: undefined,
    modifier: undefined,
  },
  {
    id: "bicycle_crunch",
    canonicalName: "Bicycle Crunch",
    aliases: ["Bicycle Crunches"],
    movementPattern: "core",
    primaryMuscles: ["core"],
    secondaryMuscles: [],
    equipment: "bodyweight",
    anchorLift: undefined,
    modifier: undefined,
  },
  {
    id: "toe_touch",
    canonicalName: "Toe Touch",
    aliases: ["Toe Touches"],
    movementPattern: "core",
    primaryMuscles: ["core"],
    secondaryMuscles: [],
    equipment: "bodyweight",
    anchorLift: undefined,
    modifier: undefined,
  },
  {
    id: "sit_up",
    canonicalName: "Sit-Up",
    aliases: ["Sit Up"],
    movementPattern: "core",
    primaryMuscles: ["core"],
    secondaryMuscles: [],
    equipment: "bodyweight",
    anchorLift: undefined,
    modifier: undefined,
  },
  {
    id: "cable_woodchop",
    canonicalName: "Cable Woodchop",
    aliases: ["Woodchop", "Cable Chop"],
    movementPattern: "core",
    primaryMuscles: ["core"],
    secondaryMuscles: [],
    equipment: "cable",
    anchorLift: undefined,
    modifier: undefined,
  },
  {
    id: "hollow_hold",
    canonicalName: "Hollow Hold",
    aliases: ["Hollow Body Hold"],
    movementPattern: "core",
    primaryMuscles: ["core"],
    secondaryMuscles: [],
    equipment: "bodyweight",
    anchorLift: undefined,
    modifier: undefined,
  },
  {
    id: "farmer_s_carry_kettlebell",
    canonicalName: "Farmer's Carry (Kettlebell)",
    aliases: ["KB Farmers Carry"],
    movementPattern: "carry",
    primaryMuscles: ["forearms"],
    secondaryMuscles: ["core", "traps"],
    equipment: "kettlebell",
    anchorLift: "deadlift",
    modifier: 0.22,
  },
  {
    id: "chest_supported_dumbbell_row",
    canonicalName: "Chest-Supported Dumbbell Row",
    aliases: ["Supported DB Row"],
    movementPattern: "horizontal_pull",
    primaryMuscles: ["back"],
    secondaryMuscles: ["biceps", "lats"],
    equipment: "dumbbell",
    anchorLift: undefined,
    modifier: undefined,
  },
  {
    id: "machine_lat_pulldown_neutral_grip",
    canonicalName: "Machine Lat Pulldown (Neutral Grip)",
    aliases: ["Neutral Grip Pulldown"],
    movementPattern: "vertical_pull",
    primaryMuscles: ["lats"],
    secondaryMuscles: ["biceps"],
    equipment: "machine",
    anchorLift: undefined,
    modifier: undefined,
  },
  {
    id: "machine_high_row",
    canonicalName: "Machine High Row",
    aliases: ["High Row"],
    movementPattern: "horizontal_pull",
    primaryMuscles: ["back"],
    secondaryMuscles: ["lats", "biceps"],
    equipment: "machine",
    anchorLift: undefined,
    modifier: undefined,
  },
  {
    id: "cable_high_row",
    canonicalName: "Cable High Row",
    aliases: ["High Cable Row"],
    movementPattern: "horizontal_pull",
    primaryMuscles: ["back"],
    secondaryMuscles: ["lats", "biceps"],
    equipment: "cable",
    anchorLift: undefined,
    modifier: undefined,
  },
  {
    id: "kneeling_lat_pulldown",
    canonicalName: "Kneeling Lat Pulldown",
    aliases: ["Kneeling Pulldown"],
    movementPattern: "vertical_pull",
    primaryMuscles: ["lats"],
    secondaryMuscles: ["biceps"],
    equipment: "cable",
    anchorLift: undefined,
    modifier: undefined,
  },
  {
    id: "pulldown_straight_bar",
    canonicalName: "Pulldown (Straight Bar)",
    aliases: ["Straight Bar Pulldown"],
    movementPattern: "vertical_pull",
    primaryMuscles: ["lats"],
    secondaryMuscles: ["biceps"],
    equipment: "cable",
    anchorLift: undefined,
    modifier: undefined,
  },
  {
    id: "machine_bicep_curl",
    canonicalName: "Machine Bicep Curl",
    aliases: ["Bicep Curl Machine"],
    movementPattern: "isolation_upper",
    primaryMuscles: ["biceps"],
    secondaryMuscles: [],
    equipment: "machine",
    anchorLift: "bench",
    modifier: 0.25,
  },
  {
    id: "cable_reverse_curl",
    canonicalName: "Cable Reverse Curl",
    aliases: ["Reverse Cable Curl"],
    movementPattern: "isolation_upper",
    primaryMuscles: ["forearms"],
    secondaryMuscles: ["biceps"],
    equipment: "cable",
    anchorLift: "bench",
    modifier: 0.2,
  },
  {
    id: "cable_wrist_curl",
    canonicalName: "Cable Wrist Curl",
    aliases: ["Wrist Curl (Cable)"],
    movementPattern: "isolation_upper",
    primaryMuscles: ["forearms"],
    secondaryMuscles: [],
    equipment: "cable",
    anchorLift: "bench",
    modifier: 0.18,
  },
  {
    id: "tricep_dip_machine",
    canonicalName: "Tricep Dip (Machine)",
    aliases: ["Dip Machine (Triceps)"],
    movementPattern: "horizontal_push",
    primaryMuscles: ["triceps"],
    secondaryMuscles: ["chest"],
    equipment: "machine",
    anchorLift: "bench",
    modifier: 0.65,
  },
  {
    id: "dumbbell_skullcrusher",
    canonicalName: "Dumbbell Skullcrusher",
    aliases: ["DB Skullcrusher"],
    movementPattern: "isolation_upper",
    primaryMuscles: ["triceps"],
    secondaryMuscles: [],
    equipment: "dumbbell",
    anchorLift: "bench",
    modifier: 0.22,
  },
  {
    id: "cable_skullcrusher",
    canonicalName: "Cable Skullcrusher",
    aliases: ["Cable Skullcrusher"],
    movementPattern: "isolation_upper",
    primaryMuscles: ["triceps"],
    secondaryMuscles: [],
    equipment: "cable",
    anchorLift: "bench",
    modifier: 0.22,
  },
  {
    id: "rear_delt_cable_fly",
    canonicalName: "Rear Delt Cable Fly",
    aliases: ["Cable Rear Delt Fly"],
    movementPattern: "isolation_upper",
    primaryMuscles: ["shoulders"],
    secondaryMuscles: ["traps"],
    equipment: "cable",
    anchorLift: "ohp",
    modifier: 0.25,
  },
  {
    id: "machine_lateral_raise",
    canonicalName: "Machine Lateral Raise",
    aliases: ["Lateral Raise Machine"],
    movementPattern: "isolation_upper",
    primaryMuscles: ["shoulders"],
    secondaryMuscles: [],
    equipment: "machine",
    anchorLift: "ohp",
    modifier: 0.3,
  },
  {
    id: "machine_rear_delt_fly",
    canonicalName: "Machine Rear Delt Fly",
    aliases: ["Rear Delt Fly Machine"],
    movementPattern: "isolation_upper",
    primaryMuscles: ["shoulders"],
    secondaryMuscles: ["traps"],
    equipment: "machine",
    anchorLift: "ohp",
    modifier: 0.3,
  },
  {
    id: "chest_fly_machine",
    canonicalName: "Chest Fly (Machine)",
    aliases: ["Machine Chest Fly"],
    movementPattern: "isolation_upper",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["shoulders"],
    equipment: "machine",
    anchorLift: "bench",
    modifier: 0.35,
  },
  {
    id: "incline_push_up",
    canonicalName: "Incline Push-Up",
    aliases: ["Incline Push Up"],
    movementPattern: "horizontal_push",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["triceps", "shoulders"],
    equipment: "bodyweight",
    anchorLift: "bench",
    modifier: 0.45,
  },
  {
    id: "cable_upright_row",
    canonicalName: "Cable Upright Row",
    aliases: ["Upright Row (Cable)"],
    movementPattern: "isolation_upper",
    primaryMuscles: ["traps"],
    secondaryMuscles: ["shoulders"],
    equipment: "cable",
    anchorLift: "deadlift",
    modifier: 0.25,
  },
  {
    id: "dumbbell_upright_row",
    canonicalName: "Dumbbell Upright Row",
    aliases: ["DB Upright Row"],
    movementPattern: "isolation_upper",
    primaryMuscles: ["traps"],
    secondaryMuscles: ["shoulders"],
    equipment: "dumbbell",
    anchorLift: "deadlift",
    modifier: 0.25,
  },
  {
    id: "barbell_upright_row",
    canonicalName: "Barbell Upright Row",
    aliases: ["BB Upright Row"],
    movementPattern: "isolation_upper",
    primaryMuscles: ["traps"],
    secondaryMuscles: ["shoulders"],
    equipment: "barbell",
    anchorLift: "deadlift",
    modifier: 0.3,
  },
  {
    id: "cable_tricep_pressdown_straight_bar",
    canonicalName: "Cable Tricep Pressdown (Straight Bar)",
    aliases: ["Straight Bar Pushdown"],
    movementPattern: "isolation_upper",
    primaryMuscles: ["triceps"],
    secondaryMuscles: [],
    equipment: "cable",
    anchorLift: "bench",
    modifier: 0.28,
  },
  {
    id: "cable_overhead_press",
    canonicalName: "Cable Overhead Press",
    aliases: ["Standing Cable Shoulder Press"],
    movementPattern: "vertical_push",
    primaryMuscles: ["shoulders"],
    secondaryMuscles: ["triceps"],
    equipment: "cable",
    anchorLift: "ohp",
    modifier: 0.55,
  },
  {
    id: "dumbbell_incline_bench_press_neutral_grip",
    canonicalName: "Dumbbell Incline Bench Press (Neutral Grip)",
    aliases: ["Neutral Grip Incline DB Press"],
    movementPattern: "horizontal_push",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["triceps", "shoulders"],
    equipment: "dumbbell",
    anchorLift: "bench",
    modifier: 0.68,
  },
  {
    id: "machine_leg_press_hack_style",
    canonicalName: "Machine Leg Press (Hack Style)",
    aliases: ["Hack Leg Press"],
    movementPattern: "squat",
    primaryMuscles: ["quads"],
    secondaryMuscles: ["glutes"],
    equipment: "machine",
    anchorLift: "squat",
    modifier: 0.85,
  },
  {
    id: "smith_machine_calf_raise",
    canonicalName: "Smith Machine Calf Raise",
    aliases: ["Smith Calf Raise"],
    movementPattern: "isolation_lower",
    primaryMuscles: ["calves"],
    secondaryMuscles: [],
    equipment: "smith",
    anchorLift: "squat",
    modifier: 0.35,
  },
  {
    id: "smith_machine_hip_thrust",
    canonicalName: "Smith Machine Hip Thrust",
    aliases: ["Smith Hip Thrust"],
    movementPattern: "hinge",
    primaryMuscles: ["glutes"],
    secondaryMuscles: ["hamstrings"],
    equipment: "smith",
    anchorLift: "deadlift",
    modifier: 0.7,
  },
  {
    id: "cable_leg_extension",
    canonicalName: "Cable Leg Extension",
    aliases: ["Leg Extension (Cable)"],
    movementPattern: "isolation_lower",
    primaryMuscles: ["quads"],
    secondaryMuscles: [],
    equipment: "cable",
    anchorLift: "squat",
    modifier: 0.25,
  },
  {
    id: "band_leg_curl",
    canonicalName: "Band Leg Curl",
    aliases: ["Leg Curl (Band)"],
    movementPattern: "isolation_lower",
    primaryMuscles: ["hamstrings"],
    secondaryMuscles: [],
    equipment: "band",
    anchorLift: "deadlift",
    modifier: 0.2,
  },
  {
    id: "banded_lateral_walk",
    canonicalName: "Banded Lateral Walk",
    aliases: ["Monster Walk"],
    movementPattern: "isolation_lower",
    primaryMuscles: ["glutes"],
    secondaryMuscles: [],
    equipment: "band",
    anchorLift: "deadlift",
    modifier: 0.18,
  },
  {
    id: "reverse_hyperextension",
    canonicalName: "Reverse Hyperextension",
    aliases: ["Reverse Hyper"],
    movementPattern: "hinge",
    primaryMuscles: ["glutes", "hamstrings"],
    secondaryMuscles: ["back"],
    equipment: "machine",
    anchorLift: "deadlift",
    modifier: 0.5,
  },
  {
    id: "kettlebell_goblet_squat",
    canonicalName: "Kettlebell Goblet Squat",
    aliases: ["KB Goblet Squat"],
    movementPattern: "squat",
    primaryMuscles: ["quads"],
    secondaryMuscles: ["glutes", "core"],
    equipment: "kettlebell",
    anchorLift: "squat",
    modifier: 0.6,
  },
  {
    id: "kettlebell_clean_press",
    canonicalName: "Kettlebell Clean & Press",
    aliases: ["KB Clean and Press"],
    movementPattern: "vertical_push",
    primaryMuscles: ["shoulders"],
    secondaryMuscles: ["core"],
    equipment: "kettlebell",
    anchorLift: "ohp",
    modifier: 0.55,
  },
  {
    id: "dumbbell_clean",
    canonicalName: "Dumbbell Clean",
    aliases: ["DB Clean"],
    movementPattern: "hinge",
    primaryMuscles: ["glutes", "hamstrings"],
    secondaryMuscles: ["back"],
    equipment: "dumbbell",
    anchorLift: "deadlift",
    modifier: 0.5,
  },
  {
    id: "battle_ropes",
    canonicalName: "Battle Ropes",
    aliases: ["Ropes"],
    movementPattern: "conditioning",
    primaryMuscles: ["shoulders"],
    secondaryMuscles: ["core"],
    equipment: "other",
    anchorLift: undefined,
    modifier: undefined,
  },
  {
    id: "box_jump",
    canonicalName: "Box Jump",
    aliases: ["Plyo Box Jump"],
    movementPattern: "conditioning",
    primaryMuscles: ["quads"],
    secondaryMuscles: ["glutes", "calves"],
    equipment: "other",
    anchorLift: undefined,
    modifier: undefined,
  },
];
